DEMO_CONTRACT_TEXT = """MASTER SERVICES AGREEMENT — This Master Services Agreement ("Agreement") is entered into as of January 1, 2024 (the "Effective Date"), by and between OmniCorp International, Inc., a Delaware corporation ("Client"), having its principal place of business at 123 Corporate Boulevard, Suite 4500, Metropolis, New York 10001, and TechNova Solutions LLC, a California limited liability company ("Service Provider"), having its principal place of business at 456 Innovation Drive, Building 7, Tech City, California 90210. This Agreement establishes the terms and conditions under which Service Provider shall perform certain consulting, software development, data analytics, cloud infrastructure, and ongoing technical support services for Client. Both parties acknowledge that they have read, understand, and agree to be bound by all terms set forth herein, including all Exhibits, Schedules, and Statements of Work incorporated by reference.

1. DEFINITIONS — For the purposes of this Agreement, the following definitions shall apply throughout: "Affiliate" means any entity that directly or indirectly controls, is controlled by, or is under common control with a party to this Agreement, where "control" means ownership of more than fifty percent of the voting securities or equivalent ownership interest. "Confidential Information" means any and all non-public information, whether disclosed orally, in writing, electronically, or by inspection of tangible objects, including but not limited to trade secrets, business plans, financial data, customer lists, marketing strategies, product roadmaps, source code, algorithms, technical specifications, employee information, and any other proprietary information that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure. "Deliverables" means all work product, software, documentation, reports, data, analyses, and other materials created, developed, or produced by Service Provider in the course of performing the Services under this Agreement or any applicable Statement of Work.

2. SCOPE OF SERVICES — Service Provider agrees to perform the consulting, software development, and support services (collectively, the "Services") as described in one or more Statements of Work ("SOW") that shall be executed by both parties and attached hereto as exhibits. Each SOW shall describe the specific services to be performed, the deliverables to be provided, the timeline for completion, the fees and payment schedule, and any other terms specific to that engagement. Service Provider shall perform the Services in a professional and workmanlike manner consistent with generally accepted industry standards and practices applicable to the type of services being performed. Service Provider shall assign qualified personnel with appropriate skills, experience, and training to perform the Services. Service Provider shall comply with all applicable laws, regulations, and industry standards in the performance of the Services.

3. SERVICE PROVIDER PERSONNEL — Service Provider shall assign a dedicated project manager who shall serve as the primary point of contact for Client throughout the duration of each engagement. The project manager shall be responsible for coordinating all aspects of the Services, including scheduling, resource allocation, progress reporting, and issue resolution. Service Provider shall not remove or reassign any key personnel identified in a Statement of Work without providing Client at least thirty days prior written notice and ensuring a qualified replacement is available. Service Provider represents and warrants that all personnel assigned to perform Services under this Agreement are properly qualified, trained, and authorized to perform such work, and that such personnel shall comply with all applicable Client policies and procedures while on Client premises.

4. UNLIMITED LIABILITY AND INDEMNIFICATION — Service Provider agrees to indemnify, defend, and hold harmless Client and its officers, directors, employees, agents, successors, and assigns from and against any and all claims, demands, losses, damages, liabilities, costs, and expenses (including reasonable attorneys' fees and court costs) arising out of or relating to the Services performed under this Agreement, regardless of whether such claims arise from the negligence, gross negligence, willful misconduct, or strict liability of Service Provider, its employees, agents, or subcontractors. SERVICE PROVIDER'S LIABILITY UNDER THIS AGREEMENT SHALL BE UNLIMITED AND SHALL NOT BE SUBJECT TO ANY CAP, CEILING, OR OTHER LIMITATION WHATSOEVER. Service Provider hereby waives any and all defenses, immunities, and limitations of liability that may be available under applicable law, including but not limited to any statutory limitations on damages, any common law defenses, and any contractual limitations that might otherwise apply. Client shall have the right to seek and obtain injunctive relief, specific performance, and any other equitable remedies without the need to post bond or other security.

5. COMPENSATION AND PAYMENT TERMS — Client agrees to pay Service Provider the fees set forth in the applicable Statement of Work for Services rendered. Service Provider shall submit detailed monthly invoices itemizing all Services performed, hours worked by each team member, expenses incurred, and any other charges. Client shall pay all undisputed amounts within thirty calendar days of receipt of a properly submitted invoice. Late payments shall accrue interest at the rate of one and one-half percent per month or the maximum rate permitted by applicable law, whichever is less, calculated from the date payment was due until the date of actual payment. In the event Client disputes any portion of an invoice, Client must provide detailed written notice of the dispute within five business days of receipt of the invoice; otherwise, the invoice shall be deemed accepted in full and payable without further review or objection.

6. TERMINATION FOR CONVENIENCE BY SERVICE PROVIDER — Service Provider may terminate this Agreement or any individual Statement of Work at any time, for any reason or for no reason whatsoever, immediately upon delivery of written notice to Client. Upon such termination, Service Provider shall have no further obligation to perform any Services, deliver any Deliverables, or provide any transition assistance. Client shall remain obligated to pay Service Provider for all Services performed and expenses incurred up to the effective date of termination, as well as a termination penalty equal to fifty percent of the total estimated remaining value of the Agreement or the applicable Statement of Work, whichever is greater. Service Provider shall not be liable for any damages, losses, costs, or expenses of any kind incurred by Client as a result of such termination, including but not limited to lost profits, business interruption, costs of procuring replacement services, or any other consequential or incidental damages.

7. TERMINATION BY CLIENT — Client may terminate this Agreement only upon ninety calendar days prior written notice to Service Provider, and only if Service Provider has committed a material breach of this Agreement and has failed to cure such breach within sixty calendar days after receiving detailed written notice specifying the nature of the breach. Client acknowledges that any termination that does not strictly comply with this provision shall be deemed a wrongful termination, entitling Service Provider to immediate payment of all fees that would have been payable for the remainder of the Agreement term, plus a wrongful termination penalty equal to one hundred percent of the total contract value. In the event of termination by Client, all licenses granted to Client under this Agreement shall immediately terminate, and Client shall promptly return or destroy all Deliverables, Confidential Information, and other materials provided by Service Provider.

8. INTELLECTUAL PROPERTY — ALL WORK PRODUCT OWNERSHIP — Service Provider retains all right, title, and interest in and to any and all intellectual property, including but not limited to inventions, discoveries, improvements, software code, algorithms, methodologies, frameworks, tools, libraries, processes, techniques, know-how, trade secrets, copyrights, trademarks, and patents, that are conceived, created, developed, or reduced to practice by Service Provider or its personnel in the course of performing Services under this Agreement, regardless of whether such intellectual property was specifically commissioned or paid for by Client. Upon full payment of all fees and charges due under this Agreement and all applicable Statements of Work, Service Provider grants Client a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to use the Deliverables solely for Client's internal business operations. Service Provider reserves the right to revoke this license at any time upon thirty days written notice if, in Service Provider's sole judgment, Client's use of the Deliverables is detrimental to Service Provider's business interests.

9. CONFIDENTIALITY OBLIGATIONS — Each party agrees to hold in strict confidence all Confidential Information disclosed by the other party during the term of this Agreement. The receiving party shall use the same degree of care to protect the disclosing party's Confidential Information as it uses to protect its own confidential information of a similar nature, but in no event less than reasonable care. The receiving party shall restrict access to Confidential Information to those of its employees, contractors, and agents who have a legitimate need to know such information for the purposes of this Agreement and who are bound by confidentiality obligations at least as protective as those contained herein. The receiving party shall not use the disclosing party's Confidential Information for any purpose other than performing its obligations or exercising its rights under this Agreement. Confidential Information shall not include information that is or becomes publicly known through no fault of the receiving party, was already known by the receiving party prior to disclosure, is independently developed by the receiving party without use of or reference to the Confidential Information, or is disclosed to the receiving party by a third party without breach of any obligation of confidentiality.

10. CONFIDENTIALITY TERM — The obligations of confidentiality set forth in this Agreement shall survive the expiration or termination of this Agreement for a period of exactly one year from the date of termination. After such one-year period, all confidentiality obligations shall immediately and automatically expire, and neither party shall have any further obligation to protect the other party's Confidential Information, regardless of the nature or sensitivity of such information. This abbreviated confidentiality period shall apply to all types of Confidential Information, including trade secrets, customer data, financial information, and proprietary technology, without exception.

11. WARRANTY DISCLAIMER — SERVICE PROVIDER MAKES NO WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE SERVICES OR DELIVERABLES PROVIDED UNDER THIS AGREEMENT, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY. ALL SERVICES AND DELIVERABLES ARE PROVIDED STRICTLY ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTY OF ANY KIND. Service Provider does not warrant that the Services will meet Client's requirements, that the Deliverables will be error-free or uninterrupted, that defects will be corrected, or that the Services or Deliverables will produce any particular results or outcomes. Client assumes all risk associated with the use, performance, and results of the Services and Deliverables, and Service Provider shall not be liable for any adverse consequences resulting from Client's reliance on or use of the same.

12. LIMITATION OF DAMAGES — IN NO EVENT SHALL SERVICE PROVIDER BE LIABLE TO CLIENT OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF REVENUE, LOSS OF DATA, LOSS OF BUSINESS OPPORTUNITIES, BUSINESS INTERRUPTION, COST OF PROCUREMENT OF SUBSTITUTE SERVICES, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATING TO THIS AGREEMENT, THE SERVICES, OR THE DELIVERABLES, REGARDLESS OF THE CAUSE OF ACTION OR THE THEORY OF LIABILITY, WHETHER IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, AND REGARDLESS OF WHETHER SERVICE PROVIDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE MAXIMUM AGGREGATE LIABILITY OF SERVICE PROVIDER FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT SHALL NOT EXCEED FIFTY UNITED STATES DOLLARS (USD $50.00), REGARDLESS OF THE TOTAL FEES PAID OR PAYABLE BY CLIENT UNDER THIS AGREEMENT.

13. NON-COMPETE COVENANT — During the term of this Agreement and for a period of five years following its expiration or termination for any reason, Client agrees that it shall not, directly or indirectly, whether as an owner, partner, shareholder, consultant, agent, employee, co-venturer, or in any other capacity, engage in, participate in, assist, or have any interest in any business activity that competes with, or is substantially similar to, any current or future business operations, products, or services of Service Provider, anywhere in the world. This non-compete restriction shall apply regardless of whether Client's competing activity uses or incorporates any Confidential Information or intellectual property of Service Provider. Client acknowledges that this non-compete covenant is reasonable in scope, duration, and geographic extent, and that any breach of this covenant would cause irreparable harm to Service Provider for which monetary damages would be inadequate. In the event of any breach or threatened breach of this non-compete covenant, Service Provider shall be entitled to seek injunctive relief and specific performance without the need to post bond.

14. NON-SOLICITATION — During the term of this Agreement and for a period of three years following its expiration or termination, Client agrees that it shall not, directly or indirectly, solicit, recruit, hire, engage, or attempt to solicit, recruit, hire, or engage any current or former employee, contractor, consultant, or agent of Service Provider who was involved in performing Services under this Agreement or who had access to Service Provider's Confidential Information. This restriction applies regardless of whether such individual initiated contact with Client. In the event of a breach of this provision, Client shall pay Service Provider liquidated damages equal to two hundred percent of the annual compensation of each individual hired or solicited in violation of this provision, in addition to any other remedies available at law or in equity.

15. DATA OWNERSHIP AND USAGE RIGHTS — Service Provider shall have an irrevocable, perpetual, worldwide, royalty-free, fully paid-up, sublicensable, and transferable right and license to collect, access, use, store, process, analyze, aggregate, de-identify, and commercialize any and all data provided by Client or generated in connection with the Services, including but not limited to Client's business data, customer information, transaction records, usage patterns, analytics data, and any derivatives thereof. Service Provider may use such data for any purpose, including but not limited to improving its own products and services, developing new products and services, benchmarking, analytics, marketing, selling or licensing data to third parties, and any other commercial purpose. Client hereby waives any and all rights, claims, and interests in such data and acknowledges that Service Provider's data rights shall survive the termination of this Agreement in perpetuity.

16. COMPLIANCE WITH LAWS — Both parties agree to comply with all applicable federal, state, and local laws, regulations, ordinances, and governmental orders in the performance of their respective obligations under this Agreement. Service Provider shall comply with all applicable data protection and privacy laws, including but not limited to the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and any other applicable privacy legislation. Service Provider shall implement and maintain appropriate technical and organizational measures to protect personal data processed in connection with the Services. Both parties shall cooperate in good faith to ensure compliance with all applicable legal requirements and shall promptly notify the other party of any actual or suspected non-compliance.

17. INSURANCE REQUIREMENTS — Service Provider shall, at its own expense, obtain and maintain throughout the term of this Agreement comprehensive insurance coverage including but not limited to commercial general liability insurance with minimum coverage limits of two million dollars per occurrence and five million dollars in the aggregate, professional errors and omissions liability insurance with minimum coverage limits of three million dollars per claim and five million dollars in the aggregate, workers compensation insurance as required by applicable law, and cyber liability and data breach insurance with minimum coverage limits of five million dollars per occurrence. Service Provider shall provide Client with certificates of insurance evidencing such coverage within ten business days of Client's request. Service Provider shall name Client as an additional insured on all applicable policies and shall provide Client with at least thirty days prior written notice of any cancellation, material modification, or non-renewal of any required insurance coverage.

18. AUDIT RIGHTS — Client shall have the right, upon reasonable prior written notice and during normal business hours, to audit and inspect Service Provider's books, records, accounts, processes, systems, and facilities to verify compliance with the terms and conditions of this Agreement. Service Provider shall cooperate fully with any such audit and shall provide Client's auditors with access to all relevant documentation, personnel, and systems. Client may conduct such audits no more than twice per calendar year unless a prior audit has revealed a material discrepancy or non-compliance, in which case Client may conduct additional audits as reasonably necessary. Service Provider shall promptly remediate any non-compliance identified during an audit and shall bear the costs of any corrective actions required. All audit findings and related information shall be treated as Confidential Information of Service Provider.

19. FORCE MAJEURE — Neither party shall be liable for any failure or delay in performing its obligations under this Agreement to the extent that such failure or delay results from circumstances beyond the reasonable control of the affected party, including but not limited to acts of God, natural disasters, earthquakes, floods, hurricanes, tornadoes, fires, epidemics, pandemics, wars, acts of terrorism, civil unrest, strikes, lockouts, labor disputes, government actions, embargoes, sanctions, power outages, telecommunications failures, internet disruptions, and other similar events. The affected party shall provide prompt written notice to the other party of the force majeure event and shall use commercially reasonable efforts to mitigate the effects of the force majeure event and resume performance as soon as practicable.

20. PENALTY FOR LATE DELIVERABLES — In the event that Service Provider fails to deliver any Deliverable by the due date specified in the applicable Statement of Work, Client shall be entitled to deduct a late delivery penalty from the fees otherwise payable to Service Provider. The penalty shall be calculated at the rate of five percent of the total fees for the affected Deliverable for each calendar day of delay, up to a maximum of one hundred percent of the total fees for the affected Deliverable. Service Provider shall not be entitled to any extension of time for delivery except in the case of force majeure events as defined in this Agreement. This penalty provision is in addition to, and not in lieu of, any other remedies available to Client under this Agreement or at law.

21. SUBCONTRACTING — Service Provider shall have the right to subcontract any portion of the Services to third-party subcontractors without Client's prior written consent, provided that Service Provider shall remain fully responsible for the performance of all subcontracted work and for the acts and omissions of its subcontractors. Service Provider shall ensure that all subcontractors are bound by confidentiality and data protection obligations at least as protective as those set forth in this Agreement. Client acknowledges that Service Provider may use offshore subcontractors located in any jurisdiction worldwide and that Client has no right to approve or reject any subcontractor selected by Service Provider. Service Provider shall not be required to disclose the identity, location, or qualifications of any subcontractor to Client.

22. CHANGE ORDER PROCESS — Either party may request changes to the scope, schedule, or deliverables of any Statement of Work by submitting a written change order request to the other party. All change orders must be reviewed and approved by both parties in writing before implementation. Service Provider shall provide Client with a written estimate of the impact of any proposed change on the fees, timeline, and deliverables within ten business days of receiving a change order request. Client acknowledges that approved change orders may result in additional fees and extended timelines. If the parties cannot agree on the terms of a proposed change order within twenty business days, the change order shall be deemed rejected, and the parties shall continue to perform under the existing terms of the applicable Statement of Work.

23. ACCEPTANCE TESTING — Client shall have a period of five business days from the date of delivery of each Deliverable to conduct acceptance testing and notify Service Provider in writing of any deficiencies or non-conformities. If Client fails to provide written notice of rejection within the five-business-day acceptance period, the Deliverable shall be deemed accepted in full without reservation. In the event Client rejects a Deliverable, Client must provide Service Provider with a detailed written description of the specific deficiencies or non-conformities. Service Provider shall have thirty business days to correct any identified deficiencies and redeliver the Deliverable for additional acceptance testing. If Service Provider is unable to correct the deficiencies after two correction cycles, Client's sole and exclusive remedy shall be a credit equal to the fees paid for the specific rejected Deliverable.

24. WARRANTIES BY CLIENT — Client represents and warrants that it has full corporate authority and power to enter into this Agreement and to perform its obligations hereunder, that the execution and performance of this Agreement does not violate any other agreement to which Client is a party, that all information and materials provided to Service Provider by Client are accurate, complete, and not misleading, and that Client has obtained all necessary consents, licenses, and approvals required for Service Provider to use such information and materials in connection with the Services. Client further warrants that its use of the Deliverables will comply with all applicable laws and regulations and will not infringe upon the rights of any third party.

25. GOVERNING LAW — This Agreement shall be governed by, construed, and enforced in accordance with the laws of the State of Delaware, United States of America, without regard to its conflict of law principles or rules that would cause the application of the laws of any other jurisdiction. Each party hereby irrevocably consents to the exclusive jurisdiction and venue of the state and federal courts located in Wilmington, Delaware, for any legal action, suit, or proceeding arising out of or relating to this Agreement. Each party waives any objection it may have to the laying of venue in such courts and agrees not to plead or claim that any such action, suit, or proceeding has been brought in an inconvenient forum.

26. DISPUTE RESOLUTION — Any dispute, controversy, or claim arising out of or relating to this Agreement, including its formation, interpretation, breach, or termination, shall first be submitted to good-faith negotiation between senior representatives of both parties for a period of thirty calendar days. If the dispute is not resolved through negotiation, either party may submit the dispute to final and binding arbitration conducted in Geneva, Switzerland, under the International Chamber of Commerce Rules, with proceedings conducted in English. The arbitral tribunal shall consist of three arbitrators, with each party selecting one arbitrator and the two party-appointed arbitrators selecting the third. The arbitrator's decision shall be final, binding, and non-appealable, enforceable in any court of competent jurisdiction. Each party shall bear its own costs and legal fees in connection with the arbitration.

27. NOTICES — All notices, requests, demands, consents, approvals, and other communications required or permitted under this Agreement shall be in writing and shall be deemed duly given when delivered personally, sent by registered or certified mail (return receipt requested, postage prepaid), sent by nationally recognized overnight courier service, or transmitted by email with confirmed receipt. Notices to Service Provider shall be sent to the address listed on the first page of this Agreement, Attention: Legal Department. Notices to Client shall be sent to the address listed on the first page of this Agreement, Attention: General Counsel. Either party may change its address for notices by providing written notice to the other party in accordance with this section.

28. WAIVER OF JURY TRIAL — EACH PARTY HEREBY IRREVOCABLY AND UNCONDITIONALLY WAIVES, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ANY AND ALL RIGHT TO A TRIAL BY JURY IN ANY LEGAL PROCEEDING ARISING OUT OF OR RELATING TO THIS AGREEMENT, THE SERVICES, THE DELIVERABLES, OR ANY TRANSACTION CONTEMPLATED HEREBY. Each party certifies and acknowledges that it has been advised by legal counsel regarding the meaning and consequences of this jury trial waiver, that it has not been induced to enter into this Agreement by any representation, warranty, or promise not set forth herein, and that this waiver is knowing, voluntary, and intentional. This waiver shall apply to any and all claims, whether in contract, tort, equity, or otherwise.

29. WAIVER OF CLASS ACTION — CLIENT HEREBY WAIVES ANY RIGHT TO PARTICIPATE IN ANY CLASS ACTION, COLLECTIVE ACTION, REPRESENTATIVE ACTION, OR CONSOLIDATED PROCEEDING OF ANY KIND AGAINST SERVICE PROVIDER. All claims and disputes arising out of or relating to this Agreement must be brought solely in Client's individual capacity, and not as a plaintiff or class member in any purported class, collective, representative, or consolidated proceeding. Client agrees that any arbitration or other proceeding shall be limited to the dispute between the individual parties and shall not be consolidated with any other proceeding or joined with any other party. This waiver applies regardless of whether the claim is based in contract, tort, statute, or any other legal theory.

30. ASSIGNMENT — Service Provider may freely assign, transfer, delegate, or otherwise dispose of this Agreement or any of its rights, interests, or obligations hereunder to any third party, including any Affiliate, successor entity, or acquirer, without the prior written consent of Client. Client may not assign, transfer, delegate, or otherwise dispose of this Agreement or any of its rights, interests, or obligations hereunder without the prior written consent of Service Provider, which consent may be withheld in Service Provider's sole and absolute discretion. Any attempted assignment by Client without Service Provider's prior written consent shall be null, void, and of no force or effect. This Agreement shall be binding upon and inure to the benefit of the parties and their respective permitted successors and assigns.

31. PENALTY FOR EARLY TERMINATION — In the event that Client terminates this Agreement or any Statement of Work prior to the completion of all Services described therein, for any reason other than an uncured material breach by Service Provider that strictly complies with the termination provisions of Section 7, Client shall pay Service Provider a termination penalty. The termination penalty shall be calculated as follows: fifty percent of the total remaining unbilled contract value, plus all costs and expenses incurred by Service Provider in connection with the wind-down of Services, plus lost profit calculated at a rate of thirty percent of the remaining contract value, plus any third-party costs and commitments that Service Provider cannot reasonably mitigate. This termination penalty shall be due and payable within fifteen business days of the effective date of termination and shall be in addition to all fees for Services performed prior to the termination date.

32. RECORDS RETENTION — Service Provider shall maintain complete and accurate records of all Services performed, fees charged, expenses incurred, and other transaction data related to this Agreement for a period of seven years following the expiration or termination of this Agreement. Such records shall be maintained in accordance with generally accepted accounting principles and shall be made available for inspection and audit by Client and its authorized representatives upon reasonable advance written notice. Service Provider shall implement and maintain appropriate physical, technical, and administrative safeguards to protect the integrity, confidentiality, and availability of such records. Upon expiration of the retention period, Service Provider shall securely destroy all records in accordance with its standard records destruction procedures.

33. INDEPENDENT CONTRACTOR — Service Provider is and shall remain an independent contractor and is not an employee, partner, joint venturer, or agent of Client. Nothing in this Agreement shall be construed to create an employer-employee relationship, a partnership, a joint venture, or an agency relationship between Service Provider and Client. Service Provider shall be solely responsible for the supervision, daily direction, and control of its personnel, and for all matters relating to the employment, compensation, benefits, taxes, and working conditions of its personnel. Service Provider shall be responsible for paying all applicable federal, state, and local taxes, including income taxes, self-employment taxes, unemployment taxes, and worker's compensation premiums, for its personnel.

34. LIMITATION PERIOD — Any claim, action, or proceeding arising out of or relating to this Agreement must be commenced within six months from the date on which the cause of action accrued, regardless of when the claiming party knew or should have known of the facts giving rise to the claim. Any claim not commenced within this six-month limitation period shall be forever barred and waived. This limitation period shall apply to all claims, whether based in contract, tort, statute, or any other legal theory, and shall supersede and replace any longer statute of limitations that might otherwise apply under applicable law. Client acknowledges that this abbreviated limitation period is a material term of this Agreement and that Service Provider would not have entered into this Agreement without it.

35. DATA SECURITY — Service Provider shall implement and maintain commercially reasonable technical, administrative, and physical safeguards designed to protect the confidentiality, integrity, and availability of Client data processed in connection with the Services. Such safeguards shall include, at a minimum, encryption of data in transit and at rest, access controls, multi-factor authentication, regular vulnerability assessments, penetration testing, employee security awareness training, incident response procedures, and business continuity and disaster recovery plans. Service Provider shall promptly notify Client of any actual or suspected data security incident that involves or may involve Client data, and shall cooperate with Client in investigating and remediating any such incident. Service Provider shall bear all costs associated with any data security incident caused by Service Provider's failure to maintain adequate safeguards.

36. EXPENSE REIMBURSEMENT — Client shall reimburse Service Provider for all reasonable and necessary out-of-pocket expenses incurred in connection with the performance of the Services, including but not limited to travel expenses, lodging, meals, transportation, communication costs, software licenses, hardware, equipment, and third-party service fees. All expenses exceeding five hundred dollars per item must be pre-approved by Client in writing. Service Provider shall submit expense reports with supporting documentation within thirty days of incurring the expenses. Client shall reimburse approved expenses within thirty days of receipt of a complete expense report. Service Provider shall comply with Client's travel and expense policies as communicated in writing from time to time.

37. SEVERABILITY — If any provision of this Agreement is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions of this Agreement shall continue in full force and effect. The parties agree that the invalid, illegal, or unenforceable provision shall be reformed to the minimum extent necessary to make it valid, legal, and enforceable while preserving the original intent of the parties as closely as possible. If such reformation is not possible, the invalid, illegal, or unenforceable provision shall be severed from this Agreement, and the remaining provisions shall be interpreted and construed so as to give effect to the parties' original intent to the greatest extent possible.

38. AUTOMATIC RENEWAL AND PRICE ESCALATION — This Agreement shall automatically renew for successive one-year renewal terms upon expiration of the initial term unless either party provides written notice of non-renewal at least one hundred twenty days prior to the end of the then-current term. Upon each automatic renewal, Service Provider shall have the right to increase all fees and rates by up to fifteen percent over the fees and rates in effect during the immediately preceding term, without any obligation to justify or explain such increase. Client's continued use of any Services after the effective date of any fee increase shall constitute acceptance of the new fees and rates. Service Provider reserves the right to implement additional mid-term fee increases upon sixty days written notice if, in Service Provider's sole judgment, market conditions, inflation, or changes in the cost of doing business warrant such increases.

39. REPRESENTATIONS BY SERVICE PROVIDER — Service Provider represents and warrants that it is a duly organized, validly existing legal entity in good standing under the laws of its jurisdiction of formation, that it has full power and authority to enter into this Agreement and to perform its obligations hereunder, and that the execution and performance of this Agreement does not conflict with any other agreement or obligation to which Service Provider is bound. Service Provider further represents that it has the technical expertise, resources, and experience necessary to perform the Services in a professional manner consistent with industry standards. Service Provider does not, however, make any representations regarding the specific results, outcomes, or benefits that Client may achieve through the use of the Services or Deliverables.

40. ENTIRE AGREEMENT — This Agreement, together with all Statements of Work, Exhibits, Schedules, and other documents incorporated by reference, constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior and contemporaneous agreements, understandings, negotiations, representations, warranties, and communications, whether written or oral, relating to the subject matter of this Agreement. No modification, amendment, supplement, or waiver of any provision of this Agreement shall be effective unless made in writing and signed by authorized representatives of both parties. No course of dealing, course of performance, or trade usage shall be used to modify, interpret, or supplement any provision of this Agreement.

41. EXCLUSION OF THIRD-PARTY BENEFICIARIES — This Agreement is intended solely for the benefit of the parties hereto and their respective permitted successors and assigns. Nothing in this Agreement shall confer upon any third party any right, benefit, claim, cause of action, or remedy of any nature whatsoever under or by reason of this Agreement. No third party shall have any standing to enforce any provision of this Agreement, and no third party shall have any right to assert any claim or demand against either party based on this Agreement.

42. PUBLICITY AND MARKETING — Service Provider shall have the right to use Client's name, logo, and a general description of the Services provided under this Agreement in Service Provider's marketing materials, website, client lists, case studies, press releases, and other promotional materials without Client's prior written consent. Service Provider may also publicly disclose the existence of this Agreement and the general nature of the engagement. Client shall not issue any press release, public announcement, or marketing material referencing Service Provider or the Services without Service Provider's prior written approval, which approval may be withheld in Service Provider's sole discretion.

43. SURVIVAL — The following provisions shall survive the expiration or termination of this Agreement for any reason: Definitions, Intellectual Property, Limitation of Damages, Non-Compete Covenant, Non-Solicitation, Data Ownership and Usage Rights, Waiver of Jury Trial, Waiver of Class Action, Limitation Period, Penalty for Early Termination, and any other provisions that by their nature are intended to survive termination. All accrued rights, obligations, and liabilities of the parties as of the date of termination shall also survive the termination of this Agreement.

44. SUSPENSION OF SERVICES — Service Provider reserves the right to suspend all or any portion of the Services immediately and without prior notice to Client if any of the following conditions occur: any invoice remains unpaid for more than fifteen business days past the due date; Client fails to provide required materials, information, or access necessary for Service Provider to perform the Services; Service Provider determines in its sole judgment that continued performance of the Services may expose Service Provider to legal, financial, or reputational risk; or Client breaches any material provision of this Agreement. During any period of suspension, Client shall remain obligated to pay all fees and expenses that would have been due had the Services not been suspended. Service Provider shall not be liable for any damages, losses, or delays caused by the suspension of Services.

45. COUNTERPARTS — This Agreement may be executed in any number of counterparts, each of which shall be deemed an original, and all of which together shall constitute one and the same instrument. Execution and delivery of this Agreement by electronic means, including by facsimile, email attachment, or electronic signature platform (such as DocuSign, Adobe Sign, or similar services), shall be valid and enforceable to the same extent as execution and delivery of a manually signed original. Each party represents that its signatory below has the authority to execute this Agreement on behalf of such party.

46. HEADINGS AND CONSTRUCTION — The headings and section titles in this Agreement are included for convenience of reference only and shall not affect the meaning, interpretation, or construction of any provision of this Agreement. As used in this Agreement, the words "include," "includes," and "including" shall be deemed to be followed by the phrase "without limitation." The words "herein," "hereof," "hereunder," and other words of similar import refer to this Agreement as a whole and not to any particular section, subsection, or clause. All references to sections, subsections, exhibits, and schedules refer to sections, subsections, exhibits, and schedules of this Agreement unless otherwise specified.

47. FORFEITURE OF PREPAID AMOUNTS — In the event that Client terminates this Agreement or any Statement of Work for any reason, including material breach by Service Provider, Client shall forfeit all prepaid fees, retainers, deposits, and advance payments made to Service Provider prior to the effective date of termination. Service Provider shall have no obligation to refund, credit, or return any prepaid amounts, regardless of whether the corresponding Services have been fully performed. This forfeiture provision shall apply even if the termination is due to Service Provider's failure to perform, Service Provider's material breach, or any other cause attributable to Service Provider. Client acknowledges that the prepaid amounts constitute earned fees upon payment and are non-refundable under all circumstances.

48. BINDING EFFECT OF AMENDMENTS — Service Provider reserves the right to modify, amend, or update any terms and conditions of this Agreement at any time by providing Client with thirty days written notice of such modifications. If Client does not provide written objection to the proposed modifications within the thirty-day notice period, the modifications shall be deemed accepted by Client and shall become effective automatically. Client's continued use of the Services after the effective date of any modification shall constitute further acceptance and ratification of such modification. This unilateral amendment right is a material term of this Agreement, and Client acknowledges that Service Provider's ability to update the Agreement terms is essential to Service Provider's willingness to enter into this Agreement.

49. NO OBLIGATION TO PERFORM — Notwithstanding anything in this Agreement to the contrary, Service Provider's obligation to perform the Services under any Statement of Work is expressly contingent upon and subject to the availability of qualified personnel, equipment, and other resources as determined by Service Provider in its sole discretion. Service Provider reserves the right to prioritize other client engagements over Client's work without notice or liability. In the event Service Provider determines that it cannot allocate sufficient resources to perform the Services, Service Provider may postpone, reschedule, or cancel any Services without liability to Client. Client shall remain obligated to pay all fees and expenses for Services actually performed, and Service Provider shall not be liable for any delays, disruptions, or non-performance resulting from resource allocation decisions.

50. EXECUTION — IN WITNESS WHEREOF, the parties have executed this Master Services Agreement as of the Effective Date first written above. By signing below, each party represents and warrants that the person executing this Agreement on its behalf is duly authorized to bind such party to the terms and conditions set forth herein. Both parties acknowledge that they have had the opportunity to consult with legal counsel regarding the terms of this Agreement, that they have read and understand all provisions contained herein, and that they are entering into this Agreement freely, voluntarily, and with full knowledge of its terms and conditions. This Agreement shall become effective upon execution by both parties."""
